version: '3.4'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: classrooms
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8888:3306
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
    networks:
      - mysql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - "./:/usr/src/app"
      - "~/.composer:/root/.composer"
    depends_on:
      - mysql
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - php
      - mysql

  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 777:80
    depends_on:
      - php
    networks:
      php: {}

networks:
  php: {}
  mysql: {}
